### ISSUE TITLE
No tests for flattattrs

### ISSUE THREAD

**Issue by schinckel** [funkybob/django-sniplates#16]

**Comment by schinckel** [comment]
Not sure what access level I need within a repo to have issues assigned to them, but feel free to assign these little ones to me if you want.

**Comment by rapilabs** [comment]
@schinckel I added a single test for flatattrs, not sure if you want to test invalid dicts or values that should be escaped as well?

**Comment by schinckel** [comment]
Yeah, I saw that, thanks.

I don't think we need to have much more: otherwise we are testing django.

It is interesting that is shows a significant difference under 1.4 (which, incidentally, I still use in production).
