### ISSUE TITLE
pypi has a version 0.5.0?

### ISSUE THREAD

**Issue by cerealcable** [funkybob/django-sniplates#56]
Doing a pip install django-sniplates ends up presenting me with 0.5.0, with a date of 2016-08-16, yet here we see releases showing Jan 25, 2016 with 0.4.1. Looks like 0.5.0 is the most current but isn't tagged here.

**Comment by funkybob** [comment]
Looks like @sergei-maertens did the 0.5.0 release, but forgot to tag it?

```
commit 1b5d8a69926b0748616d813924fb5bca944f483b
Author: Sergei Maertens <sergei-maertens@users.noreply.github.com>
Date:   Tue Aug 16 01:59:47 2016 +0200

    Prepare 0.5.0 release (#48)
```

@sergei-maertens  please tag as "release/0.5.0" if this is the case.

**Comment by sergei-maertens** [comment]
I'll double check, but afaik I don't have PyPI upload permissions.

**Comment by funkybob** [comment]
I've added the tag.

Thank's for noticing the omission, @cerealcable
