### ISSUE TITLE
default widgets set (django.html) is slightly wrong for PasswordInput

### ISSUE THREAD

**Issue by kezabelle** [funkybob/django-sniplates#57]
Subsequent to 1210d1c45848d89026872dd6ba031a5868797689 (first landing in 0.4.1), it looks like:
```
{% block PasswordInput %}{% reuse "input" input_type="password" value="" %}{% endblock %}
```
is wrong I think, `value=""` ought to be `raw_value=""` to avoid rendering anything into the `input value=""` attribute?

**Comment by sergei-maertens** [comment]
You're right, there is a test for it, but it doesn't test for a widget with value, only empty.
