### ISSUE TITLE
Release 0.7.0 to PyPI

### ISSUE THREAD

**Issue by sergei-maertens** [funkybob/django-sniplates#65]
I saw my Django 3.0 compat PR got merged and some smaller tweaks were done (thanks!) including the version bump to 0.7.0, but this hasn't been published to PyPI yet. Could you find some time to do this?

Alternatively - since I'm already maintainer on this repo, I wouldn't mind taking care of PyPI releases either :-)

**Comment by funkybob** [comment]
I was holding off a little to refine the packaging config, but will do that later.
